image: ruby:2.3
cache:
  key: "jekyll"
  paths:
    - vendor
before_script:
  - ruby -v
  - bundle install --jobs $(nproc) --path vendor
pages:
  stage: deploy
  script:
    - jekyll build -d public/
    - cp ./public/.well-known/acme-challenge/uY96f9iI304E260pyAIbJLzam1luhRq5xMGqb42QHLA.html ./public/.well-known/acme-challenge/uY96f9iI304E260pyAIbJLzam1luhRq5xMGqb42QHLA
  artifacts:
    paths:
      - public
  only:
    - master
