image: ruby:2.3
cache:
  key: "jekyll"
  paths:
    - vendor
before_script:
  - ruby -v
  - bundle install --jobs $(nproc) --path vendor
pages:
  stage: deploy
  script:
    - jekyll build -d public/
    - cp ./public/.well-known/acme-challenge/cPNAM6raqoOEoDxyxFpEFpqBWsd7luVlgYfeZI-uFaw.html ./public/.well-known/acme-challenge/cPNAM6raqoOEoDxyxFpEFpqBWsd7luVlgYfeZI-uFaw
  artifacts:
    paths:
      - public
  only:
    - master
