image: ruby:2.3
cache:
  key: "jekyll"
  paths:
    - vendor
before_script:
  - ruby -v
  - bundle install --jobs $(nproc) --path vendor
pages:
  stage: deploy
  script:
    - jekyll build -d public/
    - cp ./public/.well-known/acme-challenge/AKouL2lorzIqTj7kw-dHkVRlEcfFth7_5rUalUg8p-0.html ./public/.well-known/acme/challenge/AKouL2lorzIqTj7kw-dHkVRlEcfFth7_5rUalUg8p-0
  artifacts:
    paths:
      - public
  only:
    - master
