image: ruby:2.3
cache:
  key: "jekyll"
  paths:
    - vendor
before_script:
  - ruby -v
  - bundle install --jobs $(nproc) --path vendor
pages:
  stage: deploy
  script:
    - jekyll build -d public/
    - cp ./public/.well-known/acme-challenge/R6U9l-x8p3ni9OJkiRUKdjdIzz2r0BlDpaxpLGMVzT4.html ./public/.well-known/acme-challenge/R6U9l-x8p3ni9OJkiRUKdjdIzz2r0BlDpaxpLGMVzT4
  artifacts:
    paths:
      - public
  only:
    - master
