image: ruby:2.3
cache:
  key: "jekyll"
  paths:
    - vendor
before_script:
  - ruby -v
  - bundle install --jobs $(nproc) --path vendor
pages:
  stage: deploy
  script:
    - jekyll build -d public/
  artifacts:
    paths:
      - public
  only:
    - master
