name: Mathias Jean Johansen
email: mathias@mjj.io
permalink: "/:year/:month/:day/:title/"
url: "http://mjj.io"
markdown: kramdown
kramdown:
  input: GFM
destination: public
exclude: [vendor]
gems:
  - jekyll-sitemap
