name: Mathias Jean Johansen
permalink: "/:year/:month/:day/:title"
url: "http://mjj.io"
markdown: kramdown
kramdown:
  input: GFM
destination: public
exclude: [vendor]
sass:
  style: :compressed
  sass_dir: css
gems:
  - jekyll-sitemap
