name: Mathias Jean Johansen
email: mathias@mjj.io
permalink: "/:year/:month/:day/:title/"
url: "https://mjj.io"
markdown: kramdown
kramdown:
  input: GFM
sass:
  style: :compressed
  sass_dir: .
destination: public
exclude: [vendor]
gems:
  - jekyll-sitemap
